Hardfork aware DNS seeds
btc1/bitcoin pull request #74
Opened 2017-07-14 14:31 UTC by jgarzik

Superceding #68

2017-07-14 14:52 UTC, sneurlax commented
Not all proposed additional seeds are operational

2017-07-14 16:32 UTC, jonasschnelli commented
None of those seeds can filter by service that's not ideal for the SegWit transition IMO.
What's the reason for not supporting filtering?

Do the new seed owners have accepted the policy rule you have in your source code: https://github.com/btc1/bitcoin/blob/segwit2x/doc/dnsseed-policy.md

For the previous seeds, there are public records of the owners accepting those policies.

2017-07-14 16:35 UTC, hoffmabc commented
Well @jonasschnelli at least our intention at OB1 is to follow accepted practices but I'm not sure segwit2x seeds can actually meet some of those items in a way that would be acceptable for Bitcoin Core. Primarily the loose interpretation of 1 and 2. We would be glad to provide whatever is needed to support the general spirit of that policy though of course.

We will check on the filtering by service.

2017-07-14 16:43 UTC, jonasschnelli commented
you are sacrificing users privacy here (it's a proposal, yes) and you cannot even come up with a promis in form of a public accepted policy rule set... 

Don't excuse with a file that may require update _in your own sources_.

You move a critical infrastructure puzzle towards heavy KYCed companies.. this just feels completely wrong.

I'm speechless.

2017-07-14 16:45 UTC, hoffmabc commented
@jonasschnelli will the existing seed nodes support segwit2x?

2017-07-14 16:45 UTC, jgarzik commented
@jonasschnelli Speaking only for Bloq - same answer as @hoffmabc - Bloq will follow best practices and dnsseed-policy as closely as possible - but filtering for 2x nodes is a goal that violates strict interpretation of pt 1 and pt 2.

Really, the golden rule is just "be transparent."  In Bloq's case, we use AWS Route53.   I'm pretty sure request logging is off by default, and will take an action item to verify that.  Selection will be either sipa's machinery or a random selection of addrman addresses from a Bloq 2x node.

2017-07-14 16:48 UTC, jonasschnelli commented
That's not the point. Change the seeds to whatever you want. But just think twice again the implication for your users.
Read my post above again.

And for info:
All current seed implementions i know do not check the consensus layer.

2017-07-14 16:50 UTC, jonasschnelli commented
@jgazik: "follow as closely as possible?" I highly encourage that nobody should use btc1 regardless of if they agree or disagree with the consensus changes.

2017-07-14 16:51 UTC, bitcartel commented
It's _good_ that there are more DNS seeds, especially ones which run on infrastructure maintained and operated by companies who have the money to ensure uptime and availability.

The current DNS seeders are far from achieving the five nines, 99.999%.  Here's the average uptime sourced from http://bitcoinstats.com/network/dns-servers/

- bitseed.xf2.org 7.67%
- dnsseed.bitcoin.dashjr.org 88.10%
- dnsseed.bluematt.me 98.58%
- seed.bitcoinstats.com 98.82%
- seed.bitcoin.jonasschnelli.ch 32.26%
- seed.bitcoin.sipa.be 88.35%
- seed.bitnodes.io 98.52%
- seed.btc.petertodd.org 57.51%

Note that Bitcoin Unlimited obtains seeds not just from DNS seeders but also from Bitnodes.21.co which crawls pretty much the entire network.  See here: https://bitco.in/forum/threads/buip018-passed-bitnodes-seeding-and-user-configurable-dns-seeds.1065/

2017-07-14 16:52 UTC, christophebiocca requested changes

2017-07-14 16:52 UTC, christophebiocca commented on src/consensus/consensus.h
> +    return MAX_BASE_BLOCK_SIZE;
The changes in this file seem completely unrelated to this PR?

2017-07-14 16:58 UTC, christophebiocca commented
For those wondering why parts 1 and 2 might not be followable completely:

> 1. The DNS seed results must consist exclusively of fairly selected and functioning Bitcoin nodes from the public network to the best of the operator's understanding and capability.

So arguably part 1 would be violated by returning only 2x-supporting nodes prior to the hardfork.

> 2. For the avoidance of doubt, the results may be randomized but must not single-out any group of hosts to receive different results unless due to an urgent technical necessity and disclosed.

However I'm less clear on why part2 might not be followable, since "group of hosts" here is talking about DNS-querying-clients, not on-network nodes.

2017-07-14 17:04 UTC, hoffmabc commented
I'm just going to assume you're not directing your insults at OB1 @jonasschnelli because I really don't think anyone here has evidence that we have violated any user privacy or trust expectations during our entire existence. We also maintain seed nodes for the OpenBazaar network that follow pretty much the same guidelines. 

I know that these seed servers are like a main bastion of security for the network and to be honest I would prefer not to have to manage and be responsible for one if possible, but I will contribute where I can. I'm sorry you so disagree with the project.

2017-07-14 17:07 UTC, jgarzik commented
@christophebiocca Agreed - updated my comment to only exception re pt 1.

2017-07-14 17:07 UTC, hoffmabc commented
@christophebiocca I'm agreed @christophebiocca

2017-07-14 17:19 UTC, jonasschnelli commented
@hoffmabc: I'm not insulting. I just think you are not aware of the implications.
Moving the seeds towards KYCed companies (companies in general) changes the privacy and network fragmentation risk in a reckless way. Companies have different risks, different intentions (mostly generating revenue).

It's not about your personal intentions.


Also. Nobody has answered why all the proposed seeds do not offer filtering.

2017-07-14 17:21 UTC, hoffmabc commented
Per @cpacia "Our seed is filtering by major version so it's only returning nodes with a user-agent of /Satoshi:1.x"

2017-07-14 17:25 UTC, cpacia commented
> You move a critical infrastructure puzzle towards heavy KYCed companies.. this just feels completely wrong.

> I'm speechless.

For me this seems pretty hollow. 4 of 6 current seed operators are blockstream employees. It seems like adding these seeds adds more diversity. 

Further, the claims (by others) that this is "corporatization" if Bitcoin is extreme. All of the above are small businesses at this point. For our company it's literally just me and Brian who would maintain the seed. We could remove ob1.io and just list ourselves as individuals but I don't think it would make much difference.

2017-07-14 17:34 UTC, afk11 commented
Jeff's node has the worst uptime of them all. 

> bitseed.xf2.org 7.67%

@cpacia By my count I get 1 employee (Sipa), one contractor (Luke). Where are you getting 4 from?

2017-07-14 17:34 UTC, kek-coin commented
@cpacia I think offering to operate a seed is very generous and a laudable effort on the part of OB1 and the others. Wondering though, why don't you provide neutral seed but have opted to pre-filter by major version? Seems like you are not offering any diversity?

Stepping up and offering a hardfork-neutral seed (and letting the S2X client filter by some hardfork service bit) seems like the way to go if you are interested in adding more diversity.

2017-07-14 17:45 UTC, jonasschnelli commented
@cpacia: Diving into the blockstream conspiracy is probably inappropriate here. But the two (it's not 4)  you mentioned are working very hard since almost the beginning of the Bitcoin to secure the network and to preserve privacy on the p2p layer. A high amount of code lines in your project (btc1) was done by those (and similar motivated) developers.

But this was just my two cents and sorry for being extra grumpy today.
At the end, it up to you to secure/preserve privacy of your coin / chain.

By the way:

* ob1 seed only responses 6 IPs (and it looks like there are not more then ~15 different IPs) it's and offers no filtering. **NO IPV6 support.**
* seed.mainnet.b-pay.net **doesn't not work at all**
* blockchain.info seed only responses 6 IPs (and it looks like there are not more then ~15 different IPs) it's and offers no filtering. Curios what the reasons are why the seed also only offers 6 IPs. **NO IPV6 support.** **Pretends to support filtering but does not**
* bitcoin.bloqseeds.net seems to offer a good variety of IPs, has IPv6 support.

```
jonasschnelli@Jonass-MacBook-Pro:~/Documents/bitcoin/bitcoin$ dig A seed.ob1.io

; <<>> DiG 9.8.3-P1 <<>> A seed.ob1.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62659
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;seed.ob1.io.			IN	A

;; ANSWER SECTION:
seed.ob1.io.		4501	IN	A	80.98.131.169
seed.ob1.io.		4501	IN	A	120.24.37.119
seed.ob1.io.		4501	IN	A	121.190.114.104
seed.ob1.io.		4501	IN	A	78.61.218.12
seed.ob1.io.		4501	IN	A	46.20.246.117
seed.ob1.io.		4501	IN	A	198.61.165.63

jonasschnelli@Jonass-MacBook-Pro:~/Documents/bitcoin/bitcoin$ dig A x9.seed.ob1.io

; <<>> DiG 9.8.3-P1 <<>> A x9.seed.ob1.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7934
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;x9.seed.ob1.io.			IN	A

;; Query time: 2 msec
;; SERVER: 172.20.10.1#53(172.20.10.1)
;; WHEN: Fri Jul 14 19:37:59 2017
;; MSG SIZE  rcvd: 32


```

```
jonasschnelli@Jonass-MacBook-Pro:~/Documents/bitcoin/bitcoin$ dig A bitcoin.bloqseeds.net

; <<>> DiG 9.8.3-P1 <<>> A bitcoin.bloqseeds.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2922
;; flags: qr rd ra; QUERY: 1, ANSWER: 21, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bitcoin.bloqseeds.net.		IN	A

;; ANSWER SECTION:
bitcoin.bloqseeds.net.	2177	IN	A	164.125.215.76
bitcoin.bloqseeds.net.	2177	IN	A	109.182.65.225
bitcoin.bloqseeds.net.	2177	IN	A	99.3.144.9
bitcoin.bloqseeds.net.	2177	IN	A	88.198.230.142
bitcoin.bloqseeds.net.	2177	IN	A	142.4.214.187
bitcoin.bloqseeds.net.	2177	IN	A	192.81.211.39
bitcoin.bloqseeds.net.	2177	IN	A	209.81.9.223
bitcoin.bloqseeds.net.	2177	IN	A	24.29.251.10
bitcoin.bloqseeds.net.	2177	IN	A	2.30.83.16
bitcoin.bloqseeds.net.	2177	IN	A	195.154.214.180
bitcoin.bloqseeds.net.	2177	IN	A	35.164.42.254
bitcoin.bloqseeds.net.	2177	IN	A	81.82.201.5
bitcoin.bloqseeds.net.	2177	IN	A	45.76.167.158
bitcoin.bloqseeds.net.	2177	IN	A	208.86.162.216
bitcoin.bloqseeds.net.	2177	IN	A	173.208.216.250
bitcoin.bloqseeds.net.	2177	IN	A	47.198.4.82
bitcoin.bloqseeds.net.	2177	IN	A	178.63.57.116
bitcoin.bloqseeds.net.	2177	IN	A	163.172.42.84
bitcoin.bloqseeds.net.	2177	IN	A	88.99.214.231
bitcoin.bloqseeds.net.	2177	IN	A	90.116.20.199
bitcoin.bloqseeds.net.	2177	IN	A	163.172.221.155

;; Query time: 9 msec
;; SERVER: 172.20.10.1#53(172.20.10.1)
;; WHEN: Fri Jul 14 19:43:39 2017
;; MSG SIZE  rcvd: 375
```
```
jonasschnelli@Jonass-MacBook-Pro:~/Documents/bitcoin/bitcoin$ dig A seed.blockchain.info

; <<>> DiG 9.8.3-P1 <<>> A seed.blockchain.info
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56896
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;seed.blockchain.info.		IN	A

;; ANSWER SECTION:
seed.blockchain.info.	4188	IN	A	198.61.165.63
seed.blockchain.info.	4188	IN	A	208.185.193.190
seed.blockchain.info.	4188	IN	A	34.230.148.153
seed.blockchain.info.	4188	IN	A	148.251.182.82
seed.blockchain.info.	4188	IN	A	62.178.94.204
seed.blockchain.info.	4188	IN	A	46.20.246.117

;; Query time: 2 msec
;; SERVER: 172.20.10.1#53(172.20.10.1)
;; WHEN: Fri Jul 14 19:43:53 2017
;; MSG SIZE  rcvd: 134

jonasschnelli@Jonass-MacBook-Pro:~/Documents/bitcoin/bitcoin$ dig AAAA seed.blockchain.info

; <<>> DiG 9.8.3-P1 <<>> AAAA seed.blockchain.info
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5035
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;seed.blockchain.info.		IN	AAAA

;; AUTHORITY SECTION:
seed.blockchain.info.	3600	IN	SOA	btc-dns-seed.blockchain.info. info\@blockchain.com. 1500054071 604800 86400 2592000 604800

;; Query time: 2 msec
;; SERVER: 172.20.10.1#53(172.20.10.1)
;; WHEN: Fri Jul 14 19:44:55 2017
;; MSG SIZE  rcvd: 106

```

2017-07-14 17:46 UTC, FaysalM commented on src/consensus/consensus.h
> +    return MAX_BASE_BLOCK_SIZE;
Altho i might add the change looks good because it removes hard coding of values into a constant, but not related to this PR

2017-07-14 17:50 UTC, amtivey commented on src/consensus/consensus.h
> +    return MAX_BASE_BLOCK_SIZE;
IMO the seeds nodes shouldn't be hard-coded.  We should be able to import a list of them (as per qbittorrent etc.).

2017-07-14 19:11 UTC, michaeljs1990 commented
Why are these hard coded in the distributed binary at all? It seems like these should be in a config file that provides sane defaults and users can decide what they want to use without having to compile the code.

2017-07-14 22:01 UTC, rikur commented
Why on earth did this PR also contain a change to the max block size?

2017-07-14 22:06 UTC, hoffmabc commented
@michaeljs1990 you don't need to use them, they just are used as a fall back mechanism.

You can read an explanation here. 
https://www.reddit.com/r/Bitcoin/comments/4dicny/dns_seeds_servers_hardcoded_in_bitcoin/

I don't see why we'd need a config file for this and certainly is out of the scope of the PR.


<img width="919" alt="screen" src="https://user-images.githubusercontent.com/45482/28232512-1c592b58-68bf-11e7-916e-589e09f5890c.png">

2017-07-15 07:37 UTC, NiKiZe commented
@rikur no change in blocksize, only moved to a constant instead of magic numbers - but indeed it should not be in this PR

2017-07-15 10:20 UTC, eumartinez20 commented
Corporations adding themselves to the code as seeds is totally reckless and messes with the bitcoin network security in unimaginable ways.

Wondering if having the power to control where nodes connect belongs to the Segwit or the 2x part of the agreement.

These significant changes to the code will stop this project from succeeding. 

I am not opposed to more seeds, what I see here is two guys defending their companies should be added to the seed and excluding hundreds of others just because.

Lets add ALL companies or stick with the Segwit2x agreement and not modify this code anymore with biased changes that will definitely increase bugs and made the deadlines suffer (and general adoption decrease)

2017-07-15 12:48 UTC, JaredR26 commented
You seem to be confused about what a seed node really involves.  These will
need to be hardened against ddos attacks to an extremely high level.

Anyone who wants to run such a node should run one, with the expectation
that they are signing up to get DDOSed hard.  But despite the DDOSes, they
can't go down or change their IP.

Anyone who supports the project and is willing to harden their node against
DDOSes should be added to the list, and can.  Blockstream won't have any
nodes anyhow because every one of them has come out swinging against this
project since day one.  If they supported it, they could run a node.

Anyone else who is complaining about this issue literally has a solution at
hand- support the project, and become a node.

If you don't do either of those things, you have no right to complain about
companies who are doing so.  Those companies gain nothing at significant
expense to run these nodes with a giant target on their back.  Put up or
shut up.

2017-07-15 13:03 UTC, eumartinez20 commented
I dont know why you mention Blockstream.

So we indeed can propose seed nodes to be added to the code? That would be a step in the right direction.

2017-07-15 13:04 UTC, FaysalM commented
No one seems to want to reply or even address the fact that this PR is not atomic - and includes changes to max block size. While the changes may be fine, they should not be here and under normal circumstances they would have been rejected to do this PR again. Once again - this is what leads the wider community to believe that this is a rush job at best which will fail spectacularly and in the meanwhile kill all the credibility and good PR bitcoin received in the last few months. Kudos to you. Onwards to Litecoin now.

2017-07-15 13:21 UTC, JaredR26 commented
I can't imagine why other nodes can't be added or suggested, if it is done
quickly and there is no suspicion that the individual or company signing up
is either unable or unwilling to provide a node that helps the project.
Jeff can correct me if there's something I've missed about this.

The big issue is the DDOSes that people are signing up for.  It's something
people need to consider and prepare for.

2017-07-15 13:53 UTC, jgarzik commented
@eumartinez20 Of course you can propose seed nodes to be added!  This is an open project.  Just open an issue or PR.   We welcome new contributors.

2017-07-15 13:55 UTC, jgarzik commented
@rikur This PR does not change the max block size.   You were probably confused by a warning fix, which was initially committed to this branch, and just now moved to a separate branch.

2017-07-15 17:21 UTC, merged

2017-07-15 20:11 UTC, jonasschnelli commented
For the records:
@jgarzik: you merged a controversial pull request which adds one seed that is absolutely not working (seed.b-pay.net), one seed that seems to response static IPs with no IPv6 support (blockchain.info), one that also seems to responses static IPs (OB1) and one seed you are personally very involved (probably via company equity) (bloqseeds.net).

Non of them supports filtering by service bits.

2017-07-15 20:16 UTC, hoffmabc commented
We aren't returning statis IPs. I'm not sure what you're talking about.

2017-07-15 20:27 UTC, dgenr8 commented
@jonasschnelli Core has had 4 years to increase the block size.  How can you be surprised when the rest of the ecosystem is  forced to organize?

2017-07-17 13:13 UTC, dexX7 commented
@michaeljs1990 @hoffmabc: there is the `-seednode=<ip>` configuration option, which allows to manually add seeds.